name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Ubuntu Server
        run: |
          ssh user@your-ubuntu-server-ip << 'EOF'
          cd /path/to/your/project
          git pull origin main
          # Add any setup commands, e.g., restarting services
          python3 -m pip install -r requirements.txt
          sudo systemctl restart your-app.service
          EOF
